# Dockerfile pour créer une image avec Maven et Git
FROM maven:3.8.6-openjdk-11

# Installer Git
RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Vérifier les installations
RUN mvn --version && git --version

# Définir le répertoire de travail
WORKDIR /app

# Image prête à être utilisée par Jenkins
CMD ["bash"]
